name: Generate md5 sums
on: [push]
jobs:
  Generate-Sums:
    runs-on: ubuntu-20.04
    steps:
    - name: Generate sums
      run: |
          KERNEL_REL=5.15.0
          UBUNTU_REL=18.18
          KERNEL_BRANCH="Ubuntu-${KERNEL_REL}-${UBUNTU_REL}"
          PKGREL=1
          KERNEL_VERSION="${KERNEL_REL}-${UBUNTU_REL}-generic"
          KERNEL_REPOSITORY=git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/jammy
          APPLE_BCE_REPOSITORY=https://github.com/t2linux/apple-bce-drv.git
          APPLE_IBRIDGE_REPOSITORY=https://github.com/Redecorating/apple-ib-drv.git
          REPO_PATH=$(pwd)
          WORKING_PATH=/home/work
          KERNEL_PATH="${WORKING_PATH}/linux-kernel"
          sudo git clone --depth 1 --single-branch --branch "${KERNEL_BRANCH}" \
          "${KERNEL_REPOSITORY}" "${KERNEL_PATH}"
          cd "${KERNEL_PATH}"
          sudo tar -czvf /home/work/jammy.tar.gz *
    - name: Upload Kernel
      uses: actions/upload-artifact@v2
      with:
        name: Kernel
        path: /home/work/*.tar.gz
