name: Generate md5 sums
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Generate sums
      run: |
         sudo mkdir /work
         cd /work
         pkgver=5.13.13
         sudo wget -q https://www.kernel.org/pub/linux/kernel/v${pkgver//.*}.x/linux-${pkgver}.tar.xz
         md5sum *tar.xz
    - name: Upload Kernel
      uses: actions/upload-artifact@v2
      with:
        name: Kernel
        path: /work/*.tar.xz
