name: Generate md5 sums
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Generate sums
      run: |
         pkgver=5.13.13
         wget -q https://www.kernel.org/pub/linux/kernel/v${pkgver//.*}.x/linux-${pkgver}.tar.xz
         md5sum *tar.xz
    - name: Upload Kernel
      uses: actions/upload-artifact@v2
      with:
        name: Kernel-$(pkgver)
        path: ${{ github.workspace }}/*tar.zst
