name: Generate md5 sums
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Generate sums
      run: |
         sudo mkdir /work
         cd /work
         sudo wget -q https://github.com/AdityaGarg8/mojave-patches/raw/main/config
         sha256sum config
