name: Generate md5 sums
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Generate sums
      run: |
         KERNEL_VERSION=5.14.6
         PKGREL=1
         #KERNEL_REPOSITORY=git://kernel.ubuntu.com/virgin/linux-stable.git
         KERNEL_REPOSITORY=https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
         REPO_PATH=$(pwd)
         WORKING_PATH=/root/work
         KERNEL_PATH="${WORKING_PATH}/linux-kernel"
         apt-get update
         apt-get install -y build-essential fakeroot libncurses-dev bison flex libssl-dev libelf-dev \
         openssl dkms libudev-dev libpci-dev libiberty-dev autoconf wget xz-utils git \
         bc rsync cpio dh-modaliases debhelper kernel-wedge curl
         git clone --depth 1 --single-branch --branch "v${KERNEL_VERSION}" "${KERNEL_REPOSITORY}" "${KERNEL_PATH}"
         cd "${KERNEL_PATH}"
         make clean
         make olddefconfig
         echo "make kernelversion"
