name: Generate md5 sums
on: [push]
jobs:
  Generate-Sums:
    runs-on: ubuntu-20.04
    steps:
    - name: Generate sums
      run: |
         sudo mkdir /work
         cd /work
         sudo wget -q https://git.kernel.org/torvalds/t/linux-5.19-rc7.tar.gz
         md5sum *tar.gz
         sha256sum *tar.gz
    - name: Upload Kernel
      uses: actions/upload-artifact@v2
      with:
        name: Kernel
        path: /work/*.tar.gz
